# Header
menu:
  Home: /
  Posts: /posts
  Projects: /projects
  Résumé: /resume
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /images/fav.ico
